More AC and fixed F18C not having DDM
rkusa/dcs-scratchpad pull request #25
Opened 2022-06-27 05:43 UTC by Wamwod

-Added DMS/DDM and applied it to the hornet (the hornet uses DDM for precise bombing)
-Added both F-14 Variants to the coordsType ac list 
-Added the AV-8B to the AC List with the A10_C2
-Added A-10C because legacy

2022-06-28 13:22 UTC, rkusa requested changes
Thanks a lot for the PR! I've added an inline comment regarding the F18 change, the other additions look good to me. 👍

2022-06-28 13:22 UTC, rkusa commented on Scripts/Hooks/scratchpad-hook.lua
> +            return "DMS/DDM", true
I am pretty sure that the precisce bombing of the F18 uses DMS. You enter degrees, minutes, seconds and then decimal seconds.

Example:
```
N 13°35'12.52", E 144°55'54.11"
N 13°35.208', E 144°55.901'
55 P BR 76205 02979
168m, 551ft
```

Is entered as follows (taing lat as the example):
![image](https://user-images.githubusercontent.com/409021/176188919-2ac026da-e896-4bec-80dd-078ed435d3a7.png)
![image](https://user-images.githubusercontent.com/409021/176188995-5fc04d05-3bde-47a7-a2ed-281ac75bd446.png)

So I don't think that there is a change necessary for the F18, unless I am missing something?

2022-06-28 13:32 UTC, rkusa approved these changes

2022-06-28 13:32 UTC, merged

2022-06-28 14:41 UTC, rkusa commented
FYI, I've added some options to further adjust how DDM coordinates are displayed. This inculdes four decimal places for the F18, and a zero padded 3 width wide longitude for the F16: https://github.com/rkusa/dcs-scratchpad/blob/main/Scripts/Hooks/scratchpad-hook.lua#L277-L292

2022-06-29 09:12 UTC, Wamwod commented
Awesome this works even better 👍 I don't really code and was adding the F14 and changed the F-18 myself so I figured I'd make a PR to help others out since the F-14 wasn't added yet