Added an +NS430 button for importing Navaids to said device.
rkusa/dcs-scratchpad pull request #27
Opened 2022-06-30 08:31 UTC by Wamwod

Easily input waypoints into the NS430 using the navaids.dat file useful for making flight plans for AC without advanced navigation systems.

2022-06-30 16:38 UTC, rkusa requested changes
Cool idea, thanks for the addition!

2022-06-30 17:10 UTC, rkusa commented
Random thought, where is the `navaids.dat` saved? Because in theorie, Scratchpad could also directly write to it (as a possible future addition).

2022-06-30 22:02 UTC, Wamwod commented
> Random thought, where is the `navaids.dat` saved? Because in theorie, Scratchpad could also directly write to it (as a possible future addition).

It's stored in the main dcs folder under .\DCS World OpenBeta\Mods\aircraft\NS430\Cockpit\Scripts\avionics\terrain
I'll work on the changes and enable the button for NS430 hopefully before 0400Z

2022-07-01 00:10 UTC, Wamwod commented on Scripts/Hooks/scratchpad-hook.lua
> +            return {DDM = true, DMS = true}
I went with (2) committed and should be ready to merge LMK if there's anything else I might have overlooked.

2022-07-28 10:39 UTC, rkusa commented
Thanks again for the PR. I've resolved the conflicts and merged the PR as 255164f1d688e15dd73ca904e48a57b9a42dd3cc.

2022-07-28 10:39 UTC, closed without merging